### PR TITLE
Support for GitHub Container Registry

### PR DESCRIPTION
**Pull request by gaby**
- Add dependabot config to track updates to GitHub Actions and Docker base images.
- Add GitHub Workflow to build/publish the Docker image to GitHub Container Registry (ghcr.io).

This workflow creates the following tags:
- master/main
  - Gets updated on each merge to master/main
- latest
  - Gets updated on each new release
- semver
  - Creates tag for semver, major, major.minor

### CODE REVIEW

**Comment by abbbi** [comment]
hi,

thanks, not being familiar with release on gihub  registry, but whats the issue here?
Seems this will only work if a propper tag is pushed?

```
provenance mode=max,builder-id=https://github.com/abbbi/virtnbdbackup/actions/runs/8912936010 --tag ghcr.io/abbbi/virtnbdbackup/:master --metadata-file /home/runner/work/_temp/docker-actions-toolkit-fsVHHF/metadata-file --push docker/
ERROR: invalid tag "ghcr.io/abbbi/virtnbdbackup/:master": invalid reference format
Error: buildx failed with: ERROR: invalid tag "ghcr.io/abbbi/virtnbdbackup/:master": invalid reference format
```

**Comment by abbbi** [comment]
got it sorted. Thanks.

**Comment by gaby** [comment]
@abbbi Seems like I forgot to remove tge trailing slash when copy pasting the repo url 😂

**Comment by gaby** [comment]
Here:

```yaml
        with:
          images: |
            ghcr.io/abbbi/virtnbdbackup/
```

^ That trailing slash was the error

**Comment by gaby** [comment]
@abbbi You need to make packaged public in this repo to be able to download them. https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility#configuring-visibility-of-packages-for-your-personal-account

The image will be `ghcr.io/abbbi/virtnbdbackup:master` until a release is done, then it will get semver tagged.

**Comment by abbbi** [comment]
hi,

yes, the package options are set to public. The relase is working now, but for some reason the image published
on ghcr.io does not include the latest master checkout..:

```
docker run -it  ghcr.io/abbbi/virtnbdbackup:master virtnbdbackup -V
2.9
```

even tho i have raised the version and the publish went smooth:

https://github.com/abbbi/virtnbdbackup/actions/runs/8913997543

the only thing i noticed in the publish logs is the following message:

https://github.com/abbbi/virtnbdbackup/actions/runs/8913997543/job/24480654980#step:7:152

which is suspicious ..

**Comment by abbbi** [comment]
OK, it seems this was caused by the caching options.
I removed them and now it publishes the latest version:

```
docker run -it  ghcr.io/abbbi/virtnbdbackup:master virtnbdbackup -V
2.10
```

**Comment by gaby** [comment]
@abbbi Yeah I noticed that. I can make another PR to update the Dockerfile later.

Support for building the image during PR's can also be added (without publishing it).

**Comment by abbbi** [comment]
should be fixed by:

https://github.com/abbbi/virtnbdbackup/commit/aa34e3fd3f907296f1f221aef282f9ede19e87f0

**Comment by abbbi** [comment]
@gaby thanks, seems to work now!

**Pull request merged**
